name: _ml_for_opvs

channels:
  - conda-forge
  - pytorch
  - rdkit

# TODO: Make sure that this is correct.
dependencies:
  - python>=3.9
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pip>=20.0.2
  - pytorch>=1.4.0
  - rdkit>=2020.03.1.0
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - torchvision>=0.5.0
  - scikit-optimize>=0.9.0
  - rich >= 10.1.0
  - wandb >= 0.11.0
  - torch >= 1.9.0
  - pytorch_lightning
  - matplotlib
  - pandas
  - scikit-learn
  - pillow
  - numpy
  - xgboost
  - selfies
  - rdkit-pypi
  - yaspin
  - ipython
  - scikit-optimize
  - seaborn
