name: ml_for_opvs

channels:
  - conda-forge
  - pytorch
  - rdkit

dependencies:
  - python>=3.9
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - pandas>=1.0.3
  - pip>=20.0.2
  - pytorch>=1.4.0
  - rdkit>=2020.03.1.0
  - scikit-learn>=0.22.2.post1
  - scipy>=1.4.1
  - tensorboardX>=2.0
  - torchvision>=0.5.0
  - scikit-optimize>=0.9.0
