# python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_fabrication/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_fabrication/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_fabrication --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_fabrication/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_fabrication/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --feature_names D_A_ratio_m_m,solvent,total_solids_conc_mg_mL,solvent_additive,active_layer_thickness_nm,annealing_temperature --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_fabrication --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_electronic/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_electronic/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_electronic --random_state 22

python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_electronic/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_electronic/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --feature_names HOMO_D_eV,LUMO_D_eV,HOMO_A_eV,LUMO_A_eV --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_electronic --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_device/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_device/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_device --random_state 22

# python ../train.py --train_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_device/KFold/input_train_[0-9].csv --validation_path ../../../data/input_representation/OPV_Min/fingerprint/processed_fingerprint_device/KFold/input_valid_[0-9].csv --input_representation DA_FP_radius_3_nbits_512 --feature_names D_A_ratio_m_m,solvent,total_solids_conc_mg_mL,solvent_additive,active_layer_thickness_nm,annealing_temperature,hole_contact_layer,electron_contact_layer --target_name calc_PCE_percent --model_type RF --hyperparameter_optimization True --hyperparameter_space_path ./opv_hpo_space.json --results_path ../../../training/OPV_Min/fingerprint/processed_fingerprint_device --random_state 22